stages:

  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion//The IQ-OTHNCCD lung cancer dataset/The IQ-OTHNCCD lung cancer dataset



  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params: 
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs: 
     - artifacts/prepare_base_model


  training:
    cmd: python src/cnnClassifier/pipeline/stage_03_training.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_training.py
      - config/config.yaml
      - artifacts/data_ingestion//The IQ-OTHNCCD lung cancer dataset/The IQ-OTHNCCD lung cancer dataset
      - artifacts/prepare_base_model

    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION

    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_04_evaluation.py
    deps:
     - src/cnnClassifier/pipeline/stage_04_evaluation.py
     - config/config.yaml
     - artifacts/data_ingestion//The IQ-OTHNCCD lung cancer dataset/The IQ-OTHNCCD lung cancer dataset
     - artifacts/training/model.h5

    metrics:
    - scores.json:
       cache: false
    

